// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package repos

import (
	"github.com/joexzh/ThsConcept/db"
)

// Injectors from wire.go:

func InitStockMarketRepo() (*StockMarketRepo, error) {
	dbConfig := db.NewMysqlConfig()
	sqlDB, err := db.NewDB(dbConfig)
	if err != nil {
		return nil, err
	}
	stockMarketRepo := NewStockMarketRepo(sqlDB)
	return stockMarketRepo, nil
}
